### PR TITLE
fix(route-recognizer): a full static segment match should take precedence over a partial dynamic segment match

### PR DESCRIPTION
**Pull request by fkleuver**
fixes https://github.com/aurelia/router/issues/575

### CODE REVIEW

**Comment by davismj** [comment]
Nice work. There's a deeper issue here that I'd like to address as well. In the test case you added, if fooBar/:id? wasn't present, 'fooBar' would still match route 'foo/:id?'. It shouldn't.

I'm guessing that we actually should add an entirely new segment for this case, as the logic around DynamicSegment is insufficient.

**Comment by fkleuver** [comment]
Yeah, I kind of eluded that in my [comment](https://github.com/aurelia/router/issues/575#issuecomment-366728185) a moment ago. I thought I had it for a split second and then realized how deeply naive this solution is :-)

I only learned how this thing works just an hour ago. Should let it sink in a bit more, hah.

**Comment by fkleuver** [comment]
It's cool if you just reject this one. I'm guessing you already have a proper solution in the works and there's no point in me working on it simultaneously with the little knowledge I have of this :)

**Comment by davismj** [comment]
We always appreciate submissions from contributors! I'm here to help you by sharing what I know.

**Comment by fkleuver** [comment]
I get that, I just wanted to make sure you don't feel held up by me considering the sense of urgency you expressed in the issue

**Pull request closed without merging**
